[package]
name = "simple-codex-client"
edition.workspace = true
version.workspace = true

[dependencies]
simple-codex-core = { workspace = true }
tokio = { workspace = true }
reqwest = { workspace = true }
eventsource-stream = { workspace = true }
futures = { workspace = true }
bytes = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
